version: '3.7'
services:
    homenotify.api:
        build: ./HomeNotify.API
        ports:
            - '5000:80'
            - '5001:443'
        environment:
            - GOOGLE_CREDENTIAL=service_account_key.json
            - DB_CREDENTIALS=db_credentials_docker.json
